# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Fastvan


steps:
- task: Maven@3
  displayName: build FastVan uberJar
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: true
    goals: 'package'

- task: Maven@3
  displayName: Build Docker image
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-boot:build-image'
    publishJUnitResults: false

- task: Docker@2
  displayName: Push Docker image
  inputs:
    containerRegistry: 'Fastvan-DockerRegistry'
    repository: 'Fastvan-Demo-API'
    command: 'push'
    tags: 'latest'