# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

container: maven:3.8.1-openjdk-17-slim
variables:
  - name: JAVA_HOME_11_X64
    value: /usr/local/openjdk-17


steps:
- task: Maven@3
  displayName: build ${{ parameters.moduleName }} uberJar
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeSelection: 'path'
    jdkDirectory: '/usr/local/openjdk-17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: true
    goals: 'package'
