---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: godash-common
  name: deployment-springboot-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: springboot-app
    spec:
      containers:
        - image: 571109166839.dkr.ecr.us-east-1.amazonaws.com/godash:springboot-app_#{Build.BuildId}#
          imagePullPolicy: Always
          name: springboot-app
          ports:
            - containerPort: 8080