---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: godash-common-us
  name: deployment-springboot-app
  labels:
   app.kubernetes.io/name: springboot-app
   app.kubernetes.io/part-of: springboot-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: springboot-app
      app.kubernetes.io/part-of: springboot-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: springboot-app
        app.kubernetes.io/part-of: springboot-app
    spec:
      containers:
        - image: 571109166839.dkr.ecr.us-east-1.amazonaws.com/godash:springboot-app_#{Build.BuildId}#
          imagePullPolicy: Always
          name: springboot-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "250Mi"
              cpu: "256m"
            requests:
              memory: "250Mi"
              cpu: "256m"
      imagePullSecrets:
      - name: godash-ecr-secret      

---
apiVersion: v1
kind: Service
metadata:
  namespace: godash-common-us
  name: service-springboot-app
  labels:
    app.kubernetes.io/name: springboot-app
    app.kubernetes.io/part-of: springboot-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: springboot-app
    app.kubernetes.io/part-of: springboot-app